### PR TITLE
Add setEventListener method to HardwareDriver

### PR DESCRIPTION
**Pull request by ItsHarper**
@btelman96 I tried to test this in the remo.tv app by building an aar and by using a Gradle composite build, but both of those options gave me trouble. Could you publish a beta release?

### CODE REVIEW

**Comment by SkyeOfBreeze** [comment]
@NoahAndrews `0.14.0-beta1`
https://bintray.com/btelman96/maven/ControlSDK/0.14.0-beta1

**Comment by SkyeOfBreeze** [comment]
yeah I just find it easier to create a beta build to test things, but would be nice to find a better flow for Remo. Goal of this was to use with multiple apps, but only really has use with Remo right now.

**Comment by ItsHarper** [comment]
Alright, it works as intended! I successfully sent a chat message from `RemoBroadcaster`.

**Review by SkyeOfBreeze — APPROVED** [review]

**Comment by SkyeOfBreeze** [comment]
@NoahAndrews https://bintray.com/btelman96/maven/ControlSDK/0.14.0

**Pull request merged**
